services:
  web:
    image: thinley44/dchat-web:latest
    container_name: dchat-web
    env_file:
      - .env
    restart: always
    networks:
      network_prod:
        ipv4_address: 11.0.0.3
  ai_backend:
    image: thinley44/dchat-ai:latest
    container_name: dchat-ai
    env_file:
      - .env
    restart: always
    networks:
      network_prod:
        ipv4_address: 11.0.0.4
networks:
  network_prod:
    name: prod
    external: true
