services:
  web:
    build: .
    container_name: dchat-web
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: always
    
  db:
    image: pgvector/pgvector:pg16
    container_name: dchat-db
    env_file:
      - .env
    ports:
      - 6024:5432
    restart: always

