services:
  web:
    image: thinley44/dchat-web:latest
    env_file:
      - .env
    ports:
      -"3000:3000"
  postgres:
    image: postgres:12
    env_file:
      - .env
    ports:
      -"5432:5432"
