services:
  web:
    image: thinley44/dchat-web:latest
    container_name: dchat-web
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: always
    
  db:
    image: postgres:12
    container_name: dchat-db
    env_file:
      - .env
    ports:
      - 6024:5432
    restart: always
  
