services:
  web:
    image: thinley44/dchat-web:latest
    container_name: dchat-web
    env_file:
      - .env
    ports:
      - 3000:3000
    restart: always
    networks:
      network_prod:
        ipv4_address: 11.0.0.3
networks:
  network_prod:
    name: prod
    external: true
